language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r test_requires.txt
- pip install .
script:
- coverage run --source hemApp -m py.test
- coverage report
- coveralls
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=rickymoorhouse/hem
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
jobs:
  include:
  - stage: Docker Image
  - stage: PyPI release
    python: '3.7'
    script: echo "Publishing to PyPI"
    deploy:
      provider: pypi
      user: rickymoorhouse
      password:
        secure: 5UiATN5Dv5vNZ8nwws0NX25501KgFLcpgIK1q+J3KxR6wOXEc01d76oHYpwLAs0WQvou/yFbUITbsLUva6zGivF4igxuD+wViV5m9TzDfTfKX80hBz1Fnb3xno94uVF530voAkU7ugDCDimSG+KPRboLZrRhZaVtdD7pZgf3E9NJy+bqsVugXt4KRJQoVBSk7aUdPXZ5S2Xc5bxbw3WpsHXPvFxro8kOPrXQ7x7SjGfgyooe6g/SyrNeL23PV1ZzdkQBVcDyvkm+/G8sg0lKa6nc5WTPBSavVx+dMUUd54qYI+b2JdF7ws3GylYNoqf2PYOiJnTZYO1XGkYdORz+Ewc0Pr8k7qHKVOGhBT0zqbvUvf7FxueNEkAOpZ909HUUXdAul9p5PGTISjBzCSgRp+Xz+ki7V+QzkhVARPZxJaFwU2nmFFHdNmWsMc/PvAqAd5Zn07shIkn43dHMSpLxaY6Da6AGYTMMBwPXyUP3SYTgykaLFvIkD5hBpIuQzrDd+0p+Pd03pKqzn5ZCloSAjB8Qcu6LYhOx/HhNrc+yIOM7hfmHTpH+jYnDcVObfV2xIP0vIzs0tAU4tIGyuaz74TWbQ60NGvxICo0L5iTffH8ksGNvyNfwvXyHITnAgtIc68A6SAznCPxuzaAFo/n1hEF22A87qycXd2kHSoJa9no=
      on:
        tags: true
        branch: master
  - stage: GitHub release
    script: skip
    deploy:
      provider: releases
      api_key:
        secure: jJnnrpjIN+1ekVksml1yuyP6mcjsmSLBtzd31k4LRoW5/o4JSv1f1cvi1TIhz8eM51Z15MY3hWWkAGfnvtzsJHfASaQgANIDROxjqIAzJ/Gq8notPNqPrxPJKSUI1S923t69ZYGizLfCi78EVVuExNNJMO4YyhAmUFZOJE4Li25sg7iGQzY42ukKaqqJYXlBGJKeK8+IZbrKoX1ksfFQJ6iU6Y9gWw3TJM+AN9uw9fGjHHZTNQxUxLK7g77fXOuv4E6r7Ps3vEbav1Iu+BjjwI/+emx4bSqRmgyCybug8ypu9Ckj8qM46uWXGbZCGqWxUycrydGPuQNr1Q+Sf8dh1Q2tkUrsBNQVPmlUEuEGOe3e1uNQY7N80dNRYcKL9bj/nKrEa3nHXETtCogT+dTTbXO1/ZQ2runIfcnCdA77ETVVFNl0+fRER5G7we+tak7s1B5pEMfRvFmYfmGlwdi84XhtBruYFRxBXJJuucpLRPbF9At34Lmaf89xdRpicR7b4V19AAOBcczSHJ5lt3l+EY5jh+6Xvla+65BWFGx39vkOM3v2M/Qt8ayb/UGHzIz9oJ/FvKNLAGNL5K6G7hdQ5Ff/Ei/ejeUscYohjLQ4Qm7bKXkA48anFhLMJQXr5fTyDIIQ0oOKzxUPzO+B/ZUs0diPDKMJKJ72jLTm8NGt58E=
      file_glob: true
      file: dist/hemApp*.tar.gz
      on:
        repo: rickymoorhouse/hem
        tags: true
        branch: master
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: 241Ii4MO8hU0IDbPhZxthgQAMJXH1PVYbRlKBhUeEgzHY7I1flqjF4KnTOZ6o4Lx3SzkFXGwNbc1hFp40n9h7gVhKRu4teJA69FEsitTINtjghefx9yEY08+qv7bCU5haqiyHEcGCerf3Kf7lweYFd1SKpPpj+nvk6B2VvRUh4VqTs+ka1diP0o8BfZ7+XVIFpvCcbhk/1hyW+ddwTWR6WnJNAj4MZsFpN4zDQ/LurAq+p6vccnWY+hKV++FzXyOvgZ7ePVNJzyDkbBNEQVqvExqIaKSYEl1pOTcndhDpaRhbAqKwbhKwwtp+k5xrckeL53i64EeriJznAkgdCVtmh3Uz0yVhu7Qs52ItvOPO5eI0eqLrIDXXWM9KsVHRHA+X2QEZ8W9S8nQ2lB5TVBQGoPEfuSa0cHjDgcKlZCoqklAJGiDCdTR/tFETlq9cwUosWQ0AwFE/bBBf7MEdoKoqDIXtB2srkBDuJEDJSsSAlXoC9ZdErn1WVlj0ur6YpDrfLvKxOUS7aCc86BaD1Man2uq1b4qxK09vgAtoX5lm2I8Nz/iOcykz1CDVxdBzpVlaZ7UbxYLc0TVnPKBmE5v14JC4EQE9VAIpNO+RT5+nYgrxsvaOS0v0jTA7cu8oviYI+H91dZgaYU2E9bxzESc/jIFnO0GXjWpwejVwT2Hg/U=
  - secure: eY+bOxxzubFnEhTLMw75FGoUq5rYAmCbsthtAvPFWct6E41Q2tPV9gGPbGbv9GH5S67sA4dcMLtlH8wSvINRhvIP+kFQKBas0/a9Aqii6oAuTjY7Lyl3zPYjjbz86EcXLMWZfJ78PFdNRI8gJETVrf+yWUP/P1+6H5yt/uDTvjXm2VjEN8r9PaBrsKIUg+SUQRiV3H/Ec+Y0xkBS9fiqRt9J6VN7iwQMYtKUJxj3GuyePBpMkd7FlUBWIeStJsOv+Ls/zTVB+wEazi3LUMvpO31sRgq+bze1WzDPpnCqjUCi+4V4hJYaGiMzxO8ABH+70tpK6ezL1pbqfRzkS7Q9GsTUdXp7dqptifi608VpsnDSYcavRaCmJU6DtQerX+vaS/+XT8WECKU6lyx1flsp5lKBjrtClLe4v6cUYCTtssRCqUPXZ3hjIqFvLof2njyBWwpw5Kc6Sy95BeVlVN7g0aoFoG6JFOnUgtqwCXndeIpy9Zi2LnuJk/m0VDDLjuD25HAGw6Gsma5Ub/IV75x75M8nioCZX+yKRuElPie6Q3EtEn5jX4yo87RwHo9WafTsyA07RNEOF1mPzfbMZrrUmTDaogYqVHm+JRE8jZBxs++ECVY1bm6NpPLTXM9IQ3oO8ESKGwp5gPW6zp4z9iTte5gJc7Q1C+FaY4/FNce20Es=
  - secure: PVzgC86x+EDeGVEhXw+7v1uULFx01gjeLPUHZsS6d7S+AxSch5rF2+fMtkt+dZ48Oq4ru5br9/BwqpwxRiqYsI9RtLkOqmysnuRU6CTVn6urRhlbZyBrWIVuE3lCsbT2zCnS8Asid3mOEfMldodexEsfKSRR6V21GRpWbmDM55FjBuPI9Aaxia+g/CuHNLpKkzLeX4aldCwlaFVKJh6CyjeipA2gQDFeRnb/h+XIhdP9etIO6VBSUvfCO6wQjSTwE6NJjLKTauGvBsySgJ2P/unXbYfi913o7RmiQI0oHIZZpEGkFt1mn3/szMN2a0uToD7gXCtPyMkUhlDFDsXOBTqgRE+y43tJUcV1IcX4D5a3tyS3jLUYrihTLhReR/lom9lFESt+f+exAjd3VBo0cudwHfv0IZbHSc1g9fN+DXXvKjJ+6bGrkFZznMnq7GCdKEUP5k1mzp/xf3PYYvNhppP29cwrqg9kkXmGKeeramcqqXN+wrgZf8NCmr8xJDDH/GtE3/h3d0p7qT02UX8an0A2+FSYi03i++k0eYIqm6bnF3xU3gBZ6d5xjf0iDwtE6xgCpS+vhRses25lCOdim7SS5Kt2eiWLYXYmFVgeyU090q+6btZQMvixUY4HAKndbqIB/CzOgtMrgS+64KcnUIp9yqygqVkciRs6gUUgCNE=
