language: python
python:
- '3.5'
- '3.6'
install:
  - pip install -r test_requires.txt
  - pip install .
script:
  - coverage run --source hemApp -m py.test
  - coverage report
  - coveralls || true

jobs:
  include:
     - stage: "PyPI release"
       python: '3.5'
       script: echo "Publishing to PyPI"
       deploy:
         provider: pypi
         user: "__token__"
         password:
           secure: "bgFJiK0IQW/X2WzOckbe/B09RehBMj1CuVs/4okYFv+AgeO0ASYii52hOvus/jBFSvVhIAjOrlxYJ4WbM3XkqTptZTtfUZjgfPR/luUpaIPbW501tVfIvbrFJ3TOU/n0kYjTHhuNxzOPM00oop6ofH7Gv77QiNfyZLPUesm1zhMbtQ3Cj9v1WexrBbL6A4me3MMygyaWt/5YvqTcxLskjbdL2P+1P2GeQp9IItM4WNLCU9jPlvBcVGGSk8GqRu6NcFBzBjoqg8w6HjSKJHi/wEbPOtkFQyVkokG3MPjTHTKl05iL0IfRG+9bLMT5iBIgXQ/xbs1HMPcEjxWiuVpw0DtM31wGwr6Yw0Dx++pBT2hcKjpMCMjfg0uenMdEVl/wU70KbjniNZx7IZC7XlWesNjkdbuB08ckwfJ0wsrchXrsQqH+B1VpanQOFSSepJvUy8gV3a5VjjJC2pbrM3bMhYFhwMrEsR4IDgw2ZUA0JiXGlBtCvHipB1VX3BhdmljSG/smf4TFIU7vXZW0dg3yFGxUwFjWP7BbHNEVW0o1qinJK0vSSUSI3nwzoTuKOqmQhPxDEGbQv1J9f1eiF5hJT8+cWDsgYNXh62WkAVuFUnIC8GFo8en4X5DZqrIYaDH2zVrmLT0gvcs5OIB5ac1KVUbHDi70WyJL5VzKGs+0yog="
         on:
           tags: true
           branch: master
